libs =
import libs += libunclassified%lib{unclassified}
import libs += libriot%lib{riot}

exe{driver}: {hxx ixx txx cxx}{**} $libs testscript

cxx.poptions =+ "-I$out_root" "-I$src_root"
cxx.coptions += "-fsanitize=fuzzer,address"
